- platform: template
  sensors:
    #
    # Fuel Propane Level
    #
    heating_propane_level:
      unit_of_measurement: "%"
      icon_template: "mdi:gas-cylinder"
      # Note: entity_id is deprecated in modern templates; 
      # HA now automatically tracks entities inside the template.
      value_template: >-
        {% set raw_level = states('sensor.propane_tanks_tank_level') | float(0) %}
        {% set full_depth = 45.2 %}
        {% set offset = 0.0 %}
        
        {# Calculate the potential new percentage #}
        {% if full_depth > offset and raw_level > 0 %}
          {% set current_calc = ((raw_level - offset) / (full_depth - offset) * 100) | round(1) %}
        {% else %}
          {% set current_calc = 0 %}
        {% endif %}

        {# FILTER LOGIC: Only update if the reading is between 1% and 100% #}
        {# If it's 0 or > 100, we return the sensor's current state (self) to ignore the spike #}
        {% if 0 < current_calc <= 100 %}
          {{ current_calc }}
        {% else %}
          {{ states('sensor.heating_propane_level') | float(0) }}
        {% endif %}
    #
    # Smoke and Carbon Monixide Detectors
    #
    # Deprecated
    smoke_status:
      friendly_name: "Smoke Status"
      value_template: >-
        {% if is_state("binary_sensor.zcombo_g_smoke_co_alarm_smoke_detected", "Detected") %}
          smoke
        {% else %}
          idle
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.zcombo_g_smoke_co_alarm_smoke_detected", "Detected") %}
          mdi:fire
        {% else %}
          mdi:smoke-detector
        {% endif %}
    front_door_status:
      friendly_name: "Front_Door Status"
      value_template: >-
        {% if is_state("light.front_door_basic", "off")%}
          closed
        {% else %}
          open
        {% endif %}
      icon_template: >-
        {% if is_state("light.front_door_basic", "off")%}
          mdi:door
        {% else %}
          mdi:door-open
        {% endif %}
    garage_status:
      friendly_name: "Garage Status"
      value_template: >-
        {% if is_state("binary_sensor.ecolink_garage_door_tilt_sensor_access_control_window_door_is_open", "off")%}
          closed
        {% else %}
          open
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.ecolink_garage_door_tilt_sensor_access_control_window_door_is_open", "off")%}
          mdi:garage-variant
        {% else %}
          mdi:garage-open-variant
        {% endif %}
    flood_status:
      friendly_name: "Flood Status"
      value_template: >-
        {% if is_state("binary_sensor.flood_sensor_water_leak_state", "on")%}
          flood
        {% else %}
          dry
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.flood_sensor_water_leak_state", "on")%}
          mdi:waves
        {% else %}
          mdi:water-off
        {% endif %}


